package circuit

import (
	"errors"

	"github.com/go-chassis/go-chassis/v2/core/handler"
	"github.com/go-chassis/go-chassis/v2/core/invocation"
)

var errNextChainNoResponse = errors.New("hystrix next chain not respond")

// BizKeeperProviderHandler bizkeeper provider handler
type BizKeeperProviderHandler struct{}

// Handle handler for bizkeeper provider
func (bk *BizKeeperProviderHandler) Handle(chain *handler.Chain, i *invocation.Invocation, cb invocation.ResponseCallBack) {
	_ = "STUB: not implemented"
	return
}

// when fallback is nil, err not nil only when:
// 1. chain.Next() is executed and resp.Err is not nil
// 2. error generated by hystrix mechanism, such as ErrMaxConcurrency / ErrCircuitOpen / ErrForceFallback
//    in this case chain.Next() is not executed (r == nil)

// Name returns bizkeeper-provider string
func (bk *BizKeeperProviderHandler) Name() string { _ = "STUB: not implemented"; return "" }

func newBizKeeperProviderHandler() handler.Handler {
	_ = "STUB: not implemented"
	return *new(handler.Handler)
}
